_Django/contact/urls.py
from django.contrib import admin  # type: ignore
from . import views  
from django.urls import path  # type: ignore

app_name = 'contact'

urlpatterns = [
    path('search/', views.search, name='search'),  # type: ignore
    path('', views.index, name='index'),  # type: ignore
    
    # contact (CRUD)
    path('contact/create/', views.create, name='create'),  # type: ignore
    path('contact/<int:contact_id>/detail/', views.contact, name='contact'),  # type: ignore
    path('contact/<int:contact_id>/update/', views.update, name='update'),  # type: ignore
    path('contact/<int:contact_id>/delete/', views.delete, name='delete'),  # type: ignore
    
    # user (Create, Read, Update)
    path('user/create/', views.register, name='register'),  # type: ignore
    path('user/login/', views.login_view, name='login'),  # type: ignore
    path('user/logout/', views.logout_view, name='logout'),  # type: ignore
    path('user/update/', views.user_update, name='user_update'),  # type: ignore
    
] 

_Django/project/urls.py
# type: ignore
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('contact.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

_Django/contact/models.py
from django.db import models  # type: ignore
from django.utils import timezone  # type: ignore
from django.contrib.auth.models import User  # type: ignore

# Create your models here.

class Category(models.Model):
    class Meta():
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=50)
    
    def __str__(self) -> str:
        return self.name


class Contact(models.Model):
    # Criando campos da tabela
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=50)
    email = models.EmailField(max_length=254, blank=True)
    created_date = models.DateTimeField(default=timezone.now)
    description = models.TextField(blank=True)
    show = models.BooleanField(default=True)
    picture = models.ImageField(blank=True, upload_to='pictures/%Y/%m')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)


    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}'

_Django/contact/forms.py
from django import forms  # type: ignore
from django.core.exceptions import ValidationError  # type: ignore
from contact.models import Contact
from django.contrib.auth.forms import UserCreationForm  # type: ignore
from django.contrib.auth.models import User  # type: ignore
from django.contrib.auth import password_validation  # type: ignore


class ContactForm(forms.ModelForm):
    picture = forms.ImageField(
        widget=forms.FileInput(attrs={'accept': 'image/*'}), required=False),

    class Meta:
        model = Contact  # Modelo para criação do formulário
        # campos do formulário
        fields = 'first_name', 'last_name', 'phone', 'email', 'description', 'category', 'picture'

        # widgets = {
        #     'first_name': forms.TextInput(attrs={'placeholder': 'Nome'}),
        #     'last_name': forms.TextInput(attrs={'placeholder': 'Sobrenome'}),
        #     'phone': forms.TextInput(attrs={'placeholder': 'Telefone'}),
        #     'email': forms.EmailInput(attrs={'placeholder': 'E-mail'}),
        # }

    def clean(self):
        # cleaned_data = self.cleaned_data
        cleaned_data = self.cleaned_data
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')

        if first_name == last_name:
            msg = ValidationError(
                'Primeiro nome não pode ser igual ao segundo',
                code='invalid'
            )

            self.add_error('first_name', msg)
            self.add_error('last_name', msg)

        return super().clean()

    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')

        if first_name == 'ABC':
            self.add_error(
                'first_name',
                ValidationError(
                    'Veio do add_error',
                    code='invalid'
                )
            )

        return first_name


class RegisterForm(UserCreationForm):
    # Tornando campos obrigatórios
    first_name = forms.CharField(required=True, min_length=3)
    last_name = forms.CharField(required=True, min_length=3)
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email',
                  'username', 'password1', 'password2')

    # Validação do campo de e-mail
    def clean_email(self):
        email = self.cleaned_data.get('email')

        if User.objects.filter(email=email).exists():
            self.add_error(
                'email',  # Campo onde será mostrada a msg de erro
                ValidationError('E-mail já existe!')  # Msg que será mostrada.
            )

        return email


class RegisterUpdateForm(forms.ModelForm):
    first_name = forms.CharField(
        min_length=2,
        max_length=30,
        required=True,
        help_text='Required.',
        error_messages={
            'min_length': 'Please, add more than 2 letters.'
        }
    )
    last_name = forms.CharField(
        min_length=2,
        max_length=30,
        required=True,
        help_text='Required.'
    )

    password1 = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text=password_validation.password_validators_help_text_html(),
        required=False,
    )

    password2 = forms.CharField(
        label="Password 2",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text='Use the same password as before.',
        required=False,
    )

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email',
                  'username')

    def save(self, commit=True):
        cleaned_data = self.cleaned_data
        user = super().save(commit=False)
        password = cleaned_data.get('password1')

        if password:
            user.set_password(password)

        if commit:
            user.save()
        
        return user

    # Validação do campo de e-mail
    def clean_email(self):
        email = self.cleaned_data.get('email')
        current_email = self.instance.email

        if current_email != email:
            if User.objects.filter(email=email).exists():
                self.add_error(
                    'email',  # Campo onde será mostrada a msg de erro
                    # Msg que será mostrada.
                    ValidationError('E-mail já existe!')
                )

        return email

    def clean(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        # checando se as senhas são iguais
        if password1 or password2:
            if password1 != password2:
                self.add_error(
                    'password2',
                    ValidationError('Senhas não são iguas.')
                )

        return super().clean()

    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')

        if password1:
            try:
                password_validation.validate_password(password1)
            except ValidationError as errors:
                self.add_error(
                    'password1',
                    ValidationError(errors)
                )

        return password1

_Django/contact/views/contact_forms.py
from django.shortcuts import render, redirect, get_object_or_404  # type: ignore
from contact.forms import ContactForm
from django.urls import reverse  # type: ignore
from contact.models import Contact
from django.contrib.auth.decorators import login_required  # type: ignore


@login_required(login_url='contact:login')
def create(request):
    form_action = reverse('contact:create')

    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES)  # Dados do formulário

        context = {
            'form': form,
            'form_action': form_action,
        }

        if form.is_valid():
            contact = form.save(commit=False)
            contact.owner = request.user  # fazendo com que o contato seja proprietário dele mesmo
            contact.save()
            return redirect('contact:update', contact_id=contact.pk)

        return render(
            request,
            'contact/create.html',
            context
        )

    context = {
        'form': ContactForm(),
        'form_action': form_action,
    }

    return render(
        request,
        'contact/create.html',
        context
    )


@login_required(login_url='contact:login')
def update(request, contact_id):
    contact = get_object_or_404(Contact, pk=contact_id, show=True, owner=request.user)
    form_action = reverse('contact:update', args=(contact_id,))

    if request.method == 'POST':
        # Dados do formulário
        form = ContactForm(request.POST, request.FILES, instance=contact)

        context = {
            'form': form,
            'form_action': form_action,
        }

        if form.is_valid():
            contact = form.save()
            return redirect('contact:update', contact_id=contact.pk)

        return render(
            request,
            'contact/create.html',
            context
        )

    context = {
        'form': ContactForm(instance=contact),
        'form_action': form_action,
    }

    return render(
        request,
        'contact/create.html',
        context
    )


@login_required(login_url='contact:login')
def delete(request, contact_id):
    contact = get_object_or_404(Contact, pk=contact_id, show=True, owner=request.user)

    confirmation = request.POST.get('confirmation', 'no')

    if confirmation == 'yes':
        contact.delete()
        return redirect('contact:index')
    
    return render(
        request,
        'contact/contact.html',
        {
            'contact': contact,
            'confirmation': confirmation,
        }
    )

_Django/contact/views/contact_views.py
from django.shortcuts import render, get_object_or_404, redirect  # type: ignore
from django.db.models import Q  # type: ignore
from contact.models import Contact
from django.core.paginator import Paginator  # type: ignore


# Create your views here.
def index(request):
    contacts = Contact.objects \
        .filter(show=True)\
        .order_by('-id')

    paginator = Paginator(contacts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'site_title': 'Contatos - '
    }

    return render(
        request,
        'contact/index.html',
        context
    )


def search(request):
    search_value = request.GET.get('q', '').strip()

    if search_value == '':
        return redirect('contact:index')

    contacts = Contact.objects \
        .filter(show=True)\
        .filter(
            Q(first_name__icontains=search_value) |  # or
            Q(last_name__icontains=search_value) |
            Q(phone__icontains=search_value) |
            Q(email__icontains=search_value)
        )\
        .order_by('-id')

    paginator = Paginator(contacts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'site_title': 'Search - ',
        'search_value': search_value,
    }

    return render(
        request,
        'contact/index.html',
        context
    )


def contact(request, contact_id):
    # single_contact = Contact.objects.filter(pk=contact_id).first()
    single_contact = get_object_or_404(
        Contact, pk=contact_id, show=True
    )
    site_title = f'{single_contact.first_name} {single_contact.last_name} - '

    context = {
        'contact': single_contact,
        'site_title': site_title
    }

    return render(
        request,
        'contact/contact.html',
        context
    )

_Django/contact/views/user_forms.py
from django.shortcuts import render, redirect  # type: ignore
from django.contrib import messages, auth  # type: ignore
from contact.forms import RegisterForm, RegisterUpdateForm
from django.contrib.auth.forms import AuthenticationForm  # type: ignore
from django.contrib.auth.decorators import login_required  # type: ignore


def register(request):
    form = RegisterForm()

    # messages.info(request, 'Mensagem de INFORMAÇÃO.')
    # messages.warning(request, 'Mensagem de ATENÇÃO.')
    # messages.error(request, 'Mensagem de ERRO.')

    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, 'Usuário registrado.')
            return redirect('contact:index')

    return render(
        request,
        'contact/register.html',
        {
            'form': form
        }
    )


@login_required(login_url='contact:login')  # garantindo que o usuário esteja logado para fazer as ações abaixo
def user_update(request):
    form = RegisterUpdateForm(instance=request.user)

    if request.method != 'POST':
        return render(
            request,
            'contact/user_update.html',
            {
                'form': form
            }
        )

    form = RegisterUpdateForm(data=request.POST, instance=request.user)

    if not form.is_valid():
        return render(
            request,
            'contact/user_update.html',
            {
                'form': form
            }
        )

    form.save()
    return redirect('contact:user_update')


def login_view(request):
    form = AuthenticationForm(request)

    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)

        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)  # autenticação do login
            messages.success(request, 'Logado com sucesso!')
            return redirect('contact:index')

        messages.error(request, 'Login inválido.')

    return render(
        request,
        'contact/login.html',
        {
            'form': form
        }
    )


@login_required(login_url='contact:login')
def logout_view(request):
    auth.logout(request)
    return redirect('contact:login')

_Django/contact/templates/contact/contact.html
{% extends 'global/base.html' %}

{% block content %}
  <div class="single-contact">
    <h1 class="single-contact-name">
        {{ contact.first_name }} {{ contact.last_name }}
    </h1>
    <p><b>ID: </b>{{ contact.id }}</p>
    <p><b>E-mail: </b>{{ contact.email }}</p>
    <p><b>Phone: </b>{{ contact.phone }}</p>
    <p><b>Created Date: </b>{{ contact.created_date }}</p>
    <p><b>Description: </b>{{ contact.description }}</p>
    <p><b>Category: </b>{{ contact.category.name }}</p>

    {% if contact.picture %}
      <p>
        <img src="{{ contact.picture.url }}" alt="{{ contact.first_name }} {{ contact.last_name }}">
      </p>    
    {% endif %}

    {% if user == contact.owner %}
      <div class="contact-links">
        <a class="btn btn-link" href="{% url 'contact:update' contact.id %}">Update</a>
        
        <form action="{% url 'contact:delete' contact.id %}" method="POST"> {% csrf_token %}
          
          {% if confirmation == 'no' %}
          <button type="submit" class="btn btn-link btn-delete">Confirmar?</button>
          <input type="hidden" name="confirmation" value="yes">
          
          {% else %}
          <button type="submit" class="btn btn-link btn-delete">Delete</button>
          {% endif %}
        </form>  
      </div>
    {% endif %}
  </div>
{% endblock %}

_Django/contact/templates/contact/create.html
{% extends 'global/base.html' %}

{% block content %}
  <div class="form-wrapper">
    <h2>Contact</h2>

    <form action="{{ form_action }}" method="POST" enctype="multipart/form-data"> {% csrf_token %} {% comment %}proteção contra ataques{% endcomment %}
      {% for fields in form %}
        <div class="form-content">
          <div class="form-group">
            <label for="{{ fields.id_for_label }}">{{ fields.label }}</label>
            {{ fields }}
            {{ fields.errors }}

            {% if fields.help_text %}
              <p class="help-text">{{ fields.help_text }}</p>
            {% endif %}
                        
          </div>
        </div>
        
          {% if fields.name == 'picture' and fields.value.url%}
            <div class="form-group">
              <img src="{{ fields.value.url }}" alt="">
            </div>
          {% endif %}
        {% endfor %}
        
        <div class="form-group">
          <button class="btn" type="submit">Send</button>
        </div>
      </div>
    </form>
  </div>
{% endblock %}

_Django/contact/templates/contact/index.html
{% extends 'global/base.html' %}

{% block content %}
  {% if page_obj %}
    <div class="responsive-table">
      <table class="contacts-table">
        <caption class="table-cation">Contacts</caption>
        <thead>
          <tr class="table-row table-row-header">
            <th class="table-header">ID</th>
            <th class="table-header">First Name</th>
            <th class="table-header">Last Name</th>
            <th class="table-header">Phone</th>
            <th class="table-header">E-mail</th>
          </tr>
        </thead>
        <tbody>
          {% for contact in page_obj %}
            <tr class="table-row">
              <td class="table-cel">
                <a href="{% url 'contact:contact' contact.id %}" class="table-link">{{ contact.id }}</a>
              </td>
              <td class="table-cel">{{ contact.first_name }}</td>
              <td class="table-cel">{{ contact.last_name }}</td>
              <td class="table-cel">{{ contact.phone }}</td>
              <td class="table-cel">{{ contact.email }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>

  {% else %}
    <div class="single-contact">
      <h1 class="single-contact-name">Nenhum contato encontrado.</h1>
    </div>

  {% endif %}
{% endblock %}

_Django/contact/templates/contact/login.html
{% extends 'global/base.html' %}

{% block content %}
  <div class="form-wrapper">
    <h2>Login</h2>

    {% if user.is_authenticated %}
      <p>
        Usuário logado <b>"{{ user.username }}"</b>
        Clique <b><a href="{% url 'contact:logout' %}">aqui</a></b> para sair.
      </p>

    {% else %}
      {% include 'contact/partials/_user-form.html' %}
   
    {% endif %}
  
  </div>
{% endblock %}

_Django/contact/templates/contact/register.html
{% extends 'global/base.html' %}

{% block content %}
  <div class="form-wrapper">
    <h2>Register</h2>

    {% include "contact/partials/_user-form.html" %}

  </div>
{% endblock %}

_Django/contact/templates/contact/user_update.html
{% extends 'global/base.html' %}

{% block content %}
  <div class="form-wrapper">
    <h2>Atualização do Usuário</h2>

    {% include 'contact/partials/_user-form.html' %}
  </div>
{% endblock %}